blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>/', views.details, name='details'),
]

mainstreetbiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, legalDisclaimer, privacyPolicy, buyingProcess, about, businessFinance, sellingProcess
from listing.views import commercial, single_commercial, search_commercial, completed
from contact.views import contactSelling

urlpatterns = [
    path('', home, name='index'),
    path('legal-disclaimer/', legalDisclaimer, name='legal-disclaimer'),
    path('privacy-policy/', privacyPolicy, name='privacy-policy'),
    path('mainstreet/', admin.site.urls),
    path('buying-process/', buyingProcess, name='buying-process'),
    path('completed-deals/', completed, name='completed-deals'),
    path('business-listings/', include('listing.urls')),
    path('commercial-listings/', commercial, name='commercial-listing'),
    path('commercial-listings/search/',
         search_commercial, name='search_commercial'),
    path('commercial-listings/<int:listing_id>/',
         single_commercial, name='commercial_details'),
    path('small-business-finance/', businessFinance, name='business_finance'),
    path('selling-process/', sellingProcess, name='selling_process'),
    path('sell-your-business/', contactSelling, name='sellingPage'),
    path('blog/', include('blog.urls')),
    path('endorsements/', include('endorsement.urls')),
    path('buyers-inventory/', include('buyersregistry.urls')),
    path('about/', about, name='about'),
    path('team/', include('realtor.urls')),
    path('contact/', include('contact.urls')),
    path('downloads/', include('downloads.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('news/', include('feeds.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField


class Article(models.Model):
    title = models.CharField(max_length=500)
    subtitle = models.CharField(max_length=500, blank=True)
    slug = models.SlugField(unique=True, max_length=500)
    content = RichTextUploadingField(config_name='default')
    image = models.ImageField(upload_to='images/blog/')
    created_At = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.content[:50] + "..."

    def pretty_date(self):
        return self.created_At.strftime('%B %d , %Y')

    def save(self, *args, **kwargs):
            # Newly created object, so set slug
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)


class ImageUpload(models.Model):
    title = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.title


class ImageUploadFile(models.Model):
    image = models.FileField(upload_to='images/blog/', null=True)
    title = models.ForeignKey(
        'ImageUpload', on_delete=models.SET_NULL, null=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from .models import Article
from mainstreetbiz.views import static_query
from setting.models import MetaTags


def home(request):
    object_list = Article.objects.all().order_by('-created_At')
    meta = MetaTags.objects.filter(page_name='blog').first()
    paginator = Paginator(object_list, 6)

    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = {'articles': articles, 'meta': meta}
    context.update(static_query())
    return render(request, 'blog/blog.html', context)


def details(request, slug):
    article = Article.objects.get(slug=slug)
    context = {'article': article}
    context.update(static_query())
    return render(request, 'blog/single_post.html', context)

templates/blog/blog.html
{% extends 'layout.html' %}
{% block blog_li_class %} active {% endblock %}
{% block meta %}
<meta name="description" content="{{ meta.meta_description }}">
<meta name="keyword" content="{{ meta.meta_keyword }}">
{% endblock %}
{% block title %} {{ meta.meta_title }} {% endblock %}
{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% if articles %}
            {% for article in articles %}
            <div class="post-preview">
                <a href="{% url 'blog:details' slug=article.slug %}">
                    <h2 class="post-title">
                        {{ article.title.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ article.summary | safe }}
                    </h3>
                </a>
                <p class="post-meta">Posted by
                    <a href="#">Admin</a>
                    on {{ article.pretty_date }}</p>
            </div>
            <hr>
            {% endfor %}
            {% else %}
            <div class="m-auto col-md-12">
                <p>No Blog Post Available</p>
            </div>
            {% endif %}
            <!-- Pager -->
            <div class="clearfix">
                {% if articles.has_previous %}
                <a class="btn btn-white float-left" href="?page=1">&larr; Newer Post</a>
                {% endif %}
                {% if articles.has_next %}
                <a class="btn btn-white float-right" href="?page={{ articles.next_page_number }}">Older Posts
                    &rarr;</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<br>

{% endblock %}

templates/blog/single_post.html
{% extends 'layout.html' %}
{% block title %} {{ article.title }} {% endblock %}
{% block blog_li_class %} active {% endblock %}
{% block content %}

<section class="pt-0" id="showcase">
    <div class="home-search p-5 text-center">
        <div class="overlay-blog p-5" style="background-image:linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url({{ article.image.url }})">
            <div class="container ">
                <div class="col-lg-8 col-md-10 m-auto">
                    <div class="post-heading">
                        <h1>{{ article.title }}</h1>
                        <h2 class="subheading"> {{ article.subtitle }} </h2>
                        <span class="meta">Posted by
                            <a href="#">Admin</a>
                            on {{ article.pretty_date }} </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<article class="mb-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {{ article.content | safe }}
            </div>
        </div>
    </div>
</article>

{% endblock %}