blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>/', views.details, name='details'),
]

buyersregistry/urls.py
from django.urls import path
from .views import register, inventory
app_name = 'buyersregistry'

urlpatterns = [
    path('', inventory, name='buyers_inventory'),
    path('register/', register, name='buyers_registry')
]

mainstreetbiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, legalDisclaimer, privacyPolicy, buyingProcess, about, businessFinance, sellingProcess
from listing.views import commercial, single_commercial, search_commercial, completed
from contact.views import contactSelling

urlpatterns = [
    path('', home, name='index'),
    path('legal-disclaimer/', legalDisclaimer, name='legal-disclaimer'),
    path('privacy-policy/', privacyPolicy, name='privacy-policy'),
    path('mainstreet/', admin.site.urls),
    path('buying-process/', buyingProcess, name='buying-process'),
    path('completed-deals/', completed, name='completed-deals'),
    path('business-listings/', include('listing.urls')),
    path('commercial-listings/', commercial, name='commercial-listing'),
    path('commercial-listings/search/',
         search_commercial, name='search_commercial'),
    path('commercial-listings/<int:listing_id>/',
         single_commercial, name='commercial_details'),
    path('small-business-finance/', businessFinance, name='business_finance'),
    path('selling-process/', sellingProcess, name='selling_process'),
    path('sell-your-business/', contactSelling, name='sellingPage'),
    path('blog/', include('blog.urls')),
    path('endorsements/', include('endorsement.urls')),
    path('buyers-inventory/', include('buyersregistry.urls')),
    path('about/', about, name='about'),
    path('team/', include('realtor.urls')),
    path('contact/', include('contact.urls')),
    path('downloads/', include('downloads.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('news/', include('feeds.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buyersregistry/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField


class Register(models.Model):
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    business_type = models.CharField(max_length=50)
    investment_type = models.CharField(max_length=50)
    business_area = models.CharField(max_length=50)
    business_price = models.IntegerField()
    max_cash = models.IntegerField()
    remarks = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name + self.last_name


class BuyersDirectoryPage(models.Model):
    buyers_directory_page = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.created_at)

buyersregistry/views.py
from django.shortcuts import render, redirect
from mainstreetbiz.views import static_query
from .models import Register, BuyersDirectoryPage
from django.contrib import messages
from contact.decorators import check_recaptcha
from setting.models import MetaTags


def user_exist(email):
    users = Register.objects.all()
    for user in users:
        user_existed = None
        if user.email == email:
            user_existed = True
        else:
            user_existed = False
    return user_existed


@check_recaptcha
def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        phone = request.POST['phone']
        business_type = request.POST['business_type']
        investment_type = request.POST['investment_type']
        business_area = request.POST['business_area']
        business_price = request.POST['business_price']
        max_cash = request.POST['max_cash']
        remarks = request.POST['remarks']

        is_valid = None
        if first_name and last_name and email and phone and business_area and business_price and business_type and investment_type and max_cash and remarks != '':
            is_valid = True
        else:
            is_valid = False

        if request.recaptcha_is_valid and is_valid and ',' not in business_price and ',' not in max_cash and user_exist(email):
            user = Register(first_name=first_name, last_name=last_name, email=email, phone=phone, business_type=business_type,
                            investment_type=investment_type, business_area=business_area, business_price=business_price, max_cash=max_cash, remarks=remarks)

            user.save()
            messages.success(
                request, 'You are successfully registered with us.')
            return redirect('/buyers-inventory/register/')
        else:
            if(user_exist(email)):
                messages.warning(
                    request, 'This email is already exists.')
            else:
                messages.error(
                    request, 'Please enter valid details.')
            return redirect('/buyers-inventory/register/')
    meta = MetaTags.objects.filter(
        page_name='buyers-directory-register').first()
    context = {'meta': meta}
    context.update(static_query())
    return render(request, 'buyersregistry/register.html', context)


def inventory(request):
    buyers_directory = BuyersDirectoryPage.objects.filter().first()
    meta = MetaTags.objects.filter(page_name='buyers-directory').first()
    context = {'directory': buyers_directory, 'meta': meta}
    context.update(static_query())
    return render(request, 'buyersregistry/home.html', context)

templates/buyersregistry/home.html
{% extends 'layout.html' %}
{% load static %}
{% block directory_li_class %} active {% endblock %}
{% block meta %}
<meta name="description" content="{{ meta.meta_description }}">
<meta name="keyword" content="{{ meta.meta_keyword }}">
{% endblock %}
{% block title %} {{ meta.meta_title }} {% endblock %}
{% block content %}

<div class="disclaimer my-5">
    <div class="container">
        {{ directory.buyers_directory_page | safe }}
    </div>
</div>

{% endblock %}

templates/buyersregistry/register.html
{% extends 'layout.html' %}
{% load static %}
{% block inventory_li_class %} active {% endblock %}
{% block meta %}
<meta name="description" content="{{ meta.meta_description }}">
<meta name="keyword" content="{{ meta.meta_keyword }}">
{% endblock %}
{% block title %} {{ meta.meta_title }} {% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="mx-auto col-md-8">
            <div class="well well-sm">
                <form class="form-horizontal" action="{% url 'buyersregistry:buyers_registry' %}" method="post">
                    {% csrf_token %}
                    <fieldset>
                        <h2 class="text-center my-4">Join by registering with us.</h2>
                        {% include 'partials/_alert.html' %}
                        <small class="col-md-12">All fields are required.</small>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input name="first_name" type="text" placeholder="First Name" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input name="last_name" type="text" placeholder="Last Name" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input name="email" type="text" placeholder="Email" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                <input name="phone" type="text" placeholder="Phone" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input name="business_type" type="text" placeholder="Business type" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input name="business_area" type="text" placeholder="Business area" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input name="investment_type" type="text" placeholder="Investment type" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input name="business_price" type="text" placeholder="Business price(without ,)" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input name="max_cash" type="text" placeholder="Max Cash(without ,)" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <textarea class="form-control" name="remarks" placeholder="Remark." rows="7"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <div class="g-recaptcha" data-sitekey="6Lfo1IkUAAAAAGIAU_yPaiPD7KI5BGD8A7xecZt_"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-md">Submit</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}