blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>/', views.details, name='details'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('model', views.contactModel, name='contact_model'),
    path('', views.contact, name='contact')
]

feeds/urls.py
from django.urls import path
from .views import feeds

app_name = 'feeds'

urlpatterns = [
    path('', feeds, name='latest_feeds'),
]

listing/urls.py
from django.urls import path
from . import views

app_name = 'listing'

urlpatterns = [
    path('', views.business, name='business_listing'),
    path('search/', views.search_business, name='business_search'),
    path('<int:listing_id>/', views.single_business,
         name='business_listing_single'),
]

mainstreetbiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, legalDisclaimer, privacyPolicy, buyingProcess, about, businessFinance, sellingProcess
from listing.views import commercial, single_commercial, search_commercial, completed
from contact.views import contactSelling

urlpatterns = [
    path('', home, name='index'),
    path('legal-disclaimer/', legalDisclaimer, name='legal-disclaimer'),
    path('privacy-policy/', privacyPolicy, name='privacy-policy'),
    path('mainstreet/', admin.site.urls),
    path('buying-process/', buyingProcess, name='buying-process'),
    path('completed-deals/', completed, name='completed-deals'),
    path('business-listings/', include('listing.urls')),
    path('commercial-listings/', commercial, name='commercial-listing'),
    path('commercial-listings/search/',
         search_commercial, name='search_commercial'),
    path('commercial-listings/<int:listing_id>/',
         single_commercial, name='commercial_details'),
    path('small-business-finance/', businessFinance, name='business_finance'),
    path('selling-process/', sellingProcess, name='selling_process'),
    path('sell-your-business/', contactSelling, name='sellingPage'),
    path('blog/', include('blog.urls')),
    path('endorsements/', include('endorsement.urls')),
    path('buyers-inventory/', include('buyersregistry.urls')),
    path('about/', about, name='about'),
    path('team/', include('realtor.urls')),
    path('contact/', include('contact.urls')),
    path('downloads/', include('downloads.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('news/', include('feeds.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

realtor/urls.py
from django.urls import path
from . import views

app_name = 'realtor'

urlpatterns = [
    path('', views.team, name='team')
]

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block meta %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128566226-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-128566226-1');
    </script>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Fjord+One" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
        rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/lightbox.min.css' %}" rel="stylesheet">
</head>

<body>
    <a href="javascript:" id="return-to-top"><i class="fas fa-chevron-up"></i></a>

    <!-- Top Bar -->
    <section id="top-bar" class="p-3">
        <div class="container">
            <div class="row">
                {% include 'partials/_social_link_header.html' %}
            </div>
        </div>
    </section>
    <!-- Top Bar -->
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary sticky-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'img/logo-white.png' %}" class="logo" alt="Mainstreetbuziness">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item {% block home_li_class %} {% endblock %} mr-2">
                        <a class="nav-link" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="dropdown nav-item mr-2 {% block about_li_class %} {% endblock %}">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">About</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'realtor:team' %}">Our Team</a></li>
                            <li><a class="dropdown-item" href="{% url 'about' %}">Business</a></li>

                        </ul>
                    </li>
                    <li class="dropdown nav-item mr-2 {% block listing_li_class %} {% endblock %}">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Buying</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'buying-process' %}">Buying Process</a></li>
                            <li><a class="dropdown-item" href="{% url 'business_finance' %}">Small business finance</a></li>
                            <li><a class="dropdown-item" href="{% url 'listing:business_listing' %}">Business Listing</a></li>
                            <li><a class="dropdown-item" href="{% url 'commercial-listing' %}">Commercial Listing</a></li>
                            <li><a class="dropdown-item" href="{% url 'completed-deals' %}">Completed Deals</a></li>
                            <li><a class="dropdown-item" href="{% url 'blog:home' %}">Buyer's Blog</a></li>
                            <li><a class="dropdown-item" href="{% url 'documents:downloads' %}">Download</a></li>
                        </ul>
                    </li>
                    <li class="dropdown nav-item mr-2 {% block selling_li_class %} {% endblock %}">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Selling</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'selling_process' %}">Selling Process</a></li>
                            <li><a class="dropdown-item" href="{% url 'completed-deals' %}">Completed Deals</a></li>
                            <li><a class="dropdown-item" href="{% url 'sellingPage' %}">Sell your business</a></li>
                            <li><a class="dropdown-item" href="{% url 'blog:home' %}">Seller's Blog</a></li>
                        </ul>
                    </li>
                    <li class="dropdown nav-item mr-2 {% block directory_li_class %} {% endblock %}">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Buyers Directory</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'buyersregistry:buyers_inventory' %}">Directory</a></li>
                            <li><a class="dropdown-item" href="{% url 'buyersregistry:buyers_registry' %}">Register</a></li>
                        </ul>
                    </li>
                    <li class="{% block endorsement_li_class %} {% endblock %} nav-item mr-2">
                        <a class="nav-link" href="{% url 'endorsement:endorsements' %}">Endorsements</a></li>
                    <li class="{% block news_li_class %} {% endblock %} nav-item mr-2">
                        <a class="nav-link" href="{% url 'feeds:latest_feeds' %}">News</a></li>
                    <li class="nav-item {% block contact_li_class %} {% endblock %}mr-2">
                        <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="footer">
        <div class="container bottom_border">
            <div class="row">
                <div class=" col-sm-3 col-md col-sm-4  col-12 col">
                    <h5 class="headin5_amrc col_white_amrc pt2">Find us</h5>
                    <!--headin5_amrc-->
                    <p class="text-white">You can contact us at</p>
                    {% include 'partials/_contact_footer.html' %}
                </div>


                <div class=" col-sm-3 col-md  col-12 col">
                    <h5 class="headin5_amrc col_white_amrc pt2">Member</h5>
                    <!--headin5_amrc-->
                    <ul class="footer_ul_amrc">
                        {% for item in footer_image %}
                        <li><a href="{{ item.link }}" target="_blank"><img src="{{ item.image.url }}" alt="{{ item.name }}"
                                    style="max-width:230px;"></a></li>
                        {% endfor %}
                        <!-- <li><img src="{% static 'img/treb-logo.jpg' %}" alt="bba"> </li -->
                    </ul>
                    <!--footer_ul_amrc ends here-->
                </div>

                <div class=" col-sm-3 col-md  col-12 col">
                    <h5 class="headin5_amrc col_white_amrc pt2">Social Link</h5>
                    <!--headin5_amrc ends here-->
                    {% include 'partials/_social_link.html' %}
                    <!--footer_ul2_amrc ends here-->
                    <ul class="footer_ul3_amrc mt-3">
                        <li><a href="{% url 'legal-disclaimer' %}">Legal Disclaimer</a></li>
                        <li><a href="{% url 'privacy-policy' %}">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
        </div>


        <div class="container">
            <ul class="foote_bottom_ul_amrc">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'listing:business_listing' %}">Buying</a></li>
                <li><a href="{% url 'sellingPage' %}">Selling</a></li>
                <li><a href="{% url 'blog:home' %}">Blog</a></li>
                <li><a href="{% url 'contact:contact' %}">Contact</a></li>
            </ul>
            <!--foote_bottom_ul_amrc ends here-->
            <p class="text-center">Copyright @ <a class="footer-a" href="/">Mainstreetbiz </a><span class="year"></span>
                | Designed By
                <a class="footer-a" href="#">
                    Tej Infomedia</a></p>


            <!-- social_footer_ul ends here -->
        </div>

    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/lightbox.min.js' %}"></script>
    <!-- Custom scripts for this template -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC3JCAhNj6tVAO_LSb8M-AzMlidiT-RPAs&callback=initMap"
        async defer></script>
    <!-- Start of HubSpot Embed Code -->
    <script type="text/javascript" id="hs-script-loader" async defer src="https://js.hs-scripts.com/5102291.js"></script>
    <!-- End of HubSpot Embed Code -->

    <!-- <script>

        const nav = document.querySelector('.navbar');
        const triggers = document.querySelector('.dropdown-menu > li');

        function handleEnter() {
            console.log('enter')

        }
        console.log(triggers);

        for (let path in triggers) {
            function trigger(path) {
                console.log(path)
                return trigger.addEventListener('mouseenter', handleEnter);
            }
        }

        // Object.keys(triggers).forEach(trigger => {
        //     console.log(trigger);
        //     return trigger.addEventListener('mouseenter', handleEnter)
        // });
    </script> -->
</body>

</html>