blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>/', views.details, name='details'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('model', views.contactModel, name='contact_model'),
    path('', views.contact, name='contact')
]

listing/urls.py
from django.urls import path
from . import views

app_name = 'listing'

urlpatterns = [
    path('', views.business, name='business_listing'),
    path('search/', views.search_business, name='business_search'),
    path('<int:listing_id>/', views.single_business,
         name='business_listing_single'),
]

mainstreetbiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, legalDisclaimer, privacyPolicy, buyingProcess, about, businessFinance, sellingProcess
from listing.views import commercial, single_commercial, search_commercial, completed
from contact.views import contactSelling

urlpatterns = [
    path('', home, name='index'),
    path('legal-disclaimer/', legalDisclaimer, name='legal-disclaimer'),
    path('privacy-policy/', privacyPolicy, name='privacy-policy'),
    path('mainstreet/', admin.site.urls),
    path('buying-process/', buyingProcess, name='buying-process'),
    path('completed-deals/', completed, name='completed-deals'),
    path('business-listings/', include('listing.urls')),
    path('commercial-listings/', commercial, name='commercial-listing'),
    path('commercial-listings/search/',
         search_commercial, name='search_commercial'),
    path('commercial-listings/<int:listing_id>/',
         single_commercial, name='commercial_details'),
    path('small-business-finance/', businessFinance, name='business_finance'),
    path('selling-process/', sellingProcess, name='selling_process'),
    path('sell-your-business/', contactSelling, name='sellingPage'),
    path('blog/', include('blog.urls')),
    path('endorsements/', include('endorsement.urls')),
    path('buyers-inventory/', include('buyersregistry.urls')),
    path('about/', about, name='about'),
    path('team/', include('realtor.urls')),
    path('contact/', include('contact.urls')),
    path('downloads/', include('downloads.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('news/', include('feeds.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listing/models.py
from django.db import models
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from realtor.models import Realtor, Disclaimer
from django import forms
from adminsortable.models import SortableMixin

# Create your models here.


# switched to minimal column for data import
class BusinessListing(SortableMixin):
    status = models.CharField(max_length=100)
    business = models.CharField(max_length=200)
    business_type = models.CharField(max_length=200, blank=True, null=True)
    listing_id = models.IntegerField(unique=True)
    location = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    financing_price = models.IntegerField()
    asking_price = models.IntegerField()
    image_main = models.ImageField(upload_to='images/listings/', blank=True)
    image_1 = models.ImageField(
        upload_to='images/listings/', blank=True)
    image_2 = models.ImageField(
        upload_to='images/listings/', blank=True)
    image_3 = models.ImageField(
        upload_to='images/listings/', blank=True)
    image_4 = models.ImageField(
        upload_to='images/listings/', blank=True)
    created_at = models.DateTimeField(auto_now=True)
    nda_and_disclaimer = models.ForeignKey(
        Disclaimer, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta(object):
        ordering = ['my_order']

    my_order = models.PositiveIntegerField(
        default=0, editable=False, db_index=True)

    def __str__(self):
        return self.business

    def summary(self):
        return self.description[:50] + '...'


class CommercialListing(SortableMixin):
    status = models.CharField(max_length=100)
    business = models.CharField(max_length=200)
    business_type = models.CharField(max_length=200, blank=True, null=True)
    listing_id = models.IntegerField(unique=True)
    location = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    financing_price = models.IntegerField()
    asking_price = models.IntegerField()
    image_main = models.ImageField(upload_to='images/listings/', blank=True)
    image_1 = models.ImageField(
        upload_to='images/listings/', blank=True)
    image_2 = models.ImageField(
        upload_to='images/listings/', blank=True)
    image_3 = models.ImageField(
        upload_to='images/listings/', blank=True)
    image_4 = models.ImageField(
        upload_to='images/listings/', blank=True)
    created_at = models.DateTimeField(auto_now=True)
    nda_and_disclaimer = models.ForeignKey(
        Disclaimer, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta(object):
        ordering = ['my_order']

    my_order = models.PositiveIntegerField(
        default=0, editable=False, db_index=True)

    def __str__(self):
        return self.business

    def summary(self):
        return self.description[:50] + '...'
# class Listing(models.Model):
#     CHOICE = (('commercial', 'commercial'),
#               ('business', 'business'))
#     Type = models.CharField(max_length=20, default='business', choices=CHOICE)
#     listing_id = models.IntegerField(unique=True)
#     realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING)
#     title = models.CharField(max_length=300)
#     slug = models.SlugField(unique=True, max_length=500)
#     image_main = models.ImageField(upload_to='images/listings/')
#     image_1 = models.ImageField(
#         upload_to='images/listings/', blank=True)
#     image_2 = models.ImageField(
#         upload_to='images/listings/', blank=True)
#     image_3 = models.ImageField(
#         upload_to='images/listings/', blank=True)
#     image_4 = models.ImageField(
#         upload_to='images/listings/', blank=True)
#     area = models.ForeignKey('Area', on_delete=models.DO_NOTHING, null=True)
#     business_type = models.ForeignKey(
#         'Business_Type', on_delete=models.DO_NOTHING, null=True)
#     description = RichTextUploadingField(config_name='default')
#     price = models.IntegerField()
#     status = models.ForeignKey(
#         'Status', on_delete=models.DO_NOTHING, null=False)
#     is_published = models.BooleanField(default=True)
#     is_sold = models.BooleanField(default=False)
#     disclaimer = models.ForeignKey(Disclaimer, on_delete=models.DO_NOTHING)
#     finance = models.IntegerField(null=True)
#     created_at = models.DateTimeField(auto_now=True)
#     updated_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.title

#     def summary(self):
#         return self.description[:50] + '...'

#     def save(self, *args, **kwargs):
#             # Newly created object, so set slug
#         self.slug = slugify(self.title)
#         super(Listing, self).save(*args, **kwargs)


# class Business_Type(models.Model):
#     business_type = models.CharField(max_length=100)
#     created_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return self.business_type

#     # def save(self, *args, **kwargs):
#     #         # Newly created object, so set slug
#     #     self.business_type_slug = slugify(self.business_type)
#     #     super(Business_Type, self).save(*args, **kwargs)


# class Area(models.Model):
#     area = models.CharField(max_length=50)
#     # area_slug = models.SlugField()
#     created_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return self.area

#     # def save(self, *args, **kwargs):
#     #         # Newly created object, so set slug
#     #     self.area_slug = slugify(self.area)
#     #     super(Area, self).save(*args, **kwargs)


class Status(models.Model):
    status = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.status


class FeaturedListing(models.Model):
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/featured_image/')
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class CompletedDeals(models.Model):
    CHOICE = (('commercial', 'commercial'),
              ('business', 'business'))
    Type = models.CharField(max_length=20, default='business', choices=CHOICE)
    area = models.CharField(max_length=100)
    title = models.CharField(max_length=300)
    subtitle = models.CharField(max_length=50)
    served_as = models.CharField(max_length=50)
    completion = models.DateField()

    def __str__(self):
        return self.title


class ImageUpload(models.Model):
    title = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.title


class ImageUploadFile(models.Model):
    image = models.FileField(upload_to='images/listings/', null=True)
    title = models.ForeignKey(
        'ImageUpload', on_delete=models.SET_NULL, null=True)

listing/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .models import BusinessListing, CompletedDeals, CommercialListing
from .choices import price_choices
# Create your views here.
from mainstreetbiz.views import static_query
from setting.models import MetaTags

# For filter options

area_choices = []
businessType_choices = []


def filterSelection(BusinessListing={}, CommercialListing={}, business_category={}):
    global area_choices
    global businessType_choices
    area_choices = []
    businessType_choices = []

    # area_choices = list(set(k['area'] for k in area_list))

    if business_category == 'business':
        business_listings = BusinessListing.objects.values()
        if business_listings:
            businessType_choices = list(
                set(k['business_type'] for k in business_listings))
            area_choices = list(set(k['location'] for k in business_listings))
    elif business_category == 'commercial':
        commercial_listings = CommercialListing.objects.values()
        if commercial_listings:
            businessType_choices = list(
                set(k['business_type'] for k in commercial_listings))
            area_choices = list(set(k['location']
                                    for k in commercial_listings))
    else:
        businessType_choices = []
        area_choices = []


# for filter option
listings = BusinessListing.objects.order_by('-created_at')


def business(request):
    paginator = Paginator(listings, 12)
    page = request.GET.get('page')
    paged_listing = paginator.get_page(page)
    filterSelection(BusinessListing=BusinessListing,
                    business_category='business')
    meta = MetaTags.objects.filter(page_name='business-listing').first()
    context = {
        'list': paged_listing,
        'area': area_choices,
        'price': price_choices,
        'business_type_choice': businessType_choices,
        'form_action_url': '/business-listings/search/',
        'meta': meta,
    }
    context.update(static_query())
    return render(request, 'listing/business.html', context)


def search_business(request):
    queryset_list = listings
    filterSelection(BusinessListing=BusinessListing,
                    business_category='business')
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(
                Q(business__icontains=keywords) | Q(description__icontains=keywords))

    # for city
    if 'area' in request.GET:
        area = request.GET['area']
        if area:
            queryset_list = queryset_list.filter(
                location__icontains=area)
    # # for State
    # if 'state' in request.GET:
    #     state = request.GET['state']
    #     if state:
    #         queryset_list = queryset_list.filter(
    #             state__iexact=state)
    # for Business type
    if 'business_type' in request.GET:
        business_type = request.GET['business_type']
        if business_type:
            queryset_list = queryset_list.filter(
                business_type__icontains=business_type)
    # for price
    if 'price' in request.GET:
        price = request.GET['price']
        if price:
            queryset_list = queryset_list.filter(
                asking_price__lte=price, asking_price__gte=int(price)-100000)
    context = {
        'list': queryset_list,
        'area': area_choices,
        'price': price_choices,
        'business_type_choice': businessType_choices,
        'values': request.GET,
        'form_action_url': '/business-listings/search/'
    }
    context.update(static_query())
    return render(request, 'listing/business.html', context)


def single_business(request, listing_id):
    property = get_object_or_404(BusinessListing, listing_id=listing_id,)
    context = {'property': property}
    context.update(static_query())
    return render(request, 'listing/single_business_list.html', context)


def completed(request):
    property = CompletedDeals.objects.order_by(
        '-completion')
    meta = MetaTags.objects.filter(page_name='completed-deals').first()
    context = {'list': property, 'meta': meta}
    context.update(static_query())
    return render(request, 'listing/completed-deals.html', context)


def commercial(request):
    listings = CommercialListing.objects.order_by('-created_at')
    paginator = Paginator(listings, 12)
    page = request.GET.get('page')
    paged_listing = paginator.get_page(page)
    filterSelection(CommercialListing=CommercialListing,
                    business_category='commercial')
    meta = MetaTags.objects.filter(page_name='commercial-listing').first()
    context = {
        'list': paged_listing,
        'area': area_choices,
        'price': price_choices,
        'business_type_choice': businessType_choices,
        'form_action_url': '/commercial-listings/search/',
        'meta': meta,
    }
    context.update(static_query())
    return render(request, 'listing/commercial.html', context)


def single_commercial(request, listing_id):
    property = get_object_or_404(CommercialListing, listing_id=listing_id)
    context = {'property': property}
    context.update(static_query())
    return render(request, 'listing/single_commercial_list.html', context)


def search_commercial(request):
    queryset_list = CommercialListing.objects.order_by('-created_at')
    filterSelection(CommercialListing=CommercialListing,
                    business_category='commercial')
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(
                Q(business__icontains=keywords) | Q(description__icontains=keywords))

    # for city
    if 'area' in request.GET:
        area = request.GET['area']
        if area:
            queryset_list = queryset_list.filter(
                location__icontains=area)
    # # for State
    # if 'state' in request.GET:
    #     state = request.GET['state']
    #     if state:
    #         queryset_list = queryset_list.filter(
    #             state__iexact=state)
    # for Business type
    if 'business_type' in request.GET:
        business_type = request.GET['business_type']
        print(business_type)
        if business_type:
            queryset_list = queryset_list.filter(
                business_type__icontains=business_type)
    # for price
    if 'price' in request.GET:
        price = request.GET['price']
        if price:
            queryset_list = queryset_list.filter(
                asking_price__lte=price, asking_price__gte=int(price)-100000)
    context = {
        'list': queryset_list,
        'area': area_choices,
        'price': price_choices,
        'business_type_choice': businessType_choices,
        'values': request.GET,
        'form_action_url': '/commercial-listings/search/'
    }
    context.update(static_query())
    return render(request, 'listing/commercial.html', context)

templates/listing/business.html
{% extends 'layout.html' %}
{% load static %}
{% load humanize %}
{% block listing_li_class %} active {% endblock %}
{% block meta %}
<meta name="description" content="{{ meta.meta_description }}">
<meta name="keyword" content="{{ meta.meta_keyword }}">
{% endblock %}
{% block title %} {{ meta.meta_title }} {% endblock %}
{% block content %}
{% include 'partials/_search_box.html'%}

<div class="py-5">
  <div class="container">
    <div class="row">
      {% if list %}
      {% for list_item in list %}
      <div class="col-md-3">
        <div class="card mt-5 shadow-sm">
          <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail"
            alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{ list_item.image_main.url }}" />
          <div class="card-img-overlay">
            <h2>
              <span class="badge badge-primary text-dark">${{ list_item.asking_price | intcomma }}</span>
            </h2>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">{{ list_item.location }}</li>
            <li class="list-group-item">{{ list_item.business }}</li>
            <li class="list-group-item">{{ list_item.summary | safe }} </li>
            <li class="list-group-item">Status: {{ list_item.status }}</li>
          </ul>
          <div class="card-body justify-content-between align-items-center">
            <div class="btn-group">
              <a href="{% url 'listing:business_listing_single' list_item.listing_id %}">
                <button type="button" class="btn btn-sm btn-primary">More
                  Details..</button>
              </a>
            </div>
          </div>
        </div>
      </div>

      {% endfor %}
      {% else %}
      <div class="col-md-12">
        <h1 class="text-center">No Listing Available</h1>
      </div>
      {% endif %}
      <!-- Pagination -->
      <div class="col-md-12 mt-5">
        <nav aria-label="Page navigation ">
          <ul class="pagination justify-content-center">
            {% if list.has_other_pages %}
            {% if list.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ list.previous_page_number }}" tabindex="-1">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="" tabindex="-1">Previous</a>
            </li>
            {% endif %}
            {% for i in list.paginator.page_range %}
            {% if list.number == i %}
            <li class="page-item active"><a class="page-link " href="">{{ i }}</a>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link " href="?page={{i}}">{{ i }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if list.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ list.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="" tabindex="-1">Next</a>
            </li>
            {% endif %}
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>


{% endblock%}

templates/listing/search.html
{% extends 'layout.html' %}
{% block title %} Search {% endblock %}
{% block listing_li_class %} active {% endblock %}
{% load static %}
{% load humanize %}

{% block content %}

{% include 'partials/_search_box.html' %}

<div class="pb-3">
    <div class="container">
        <div class="row">
            {% if list %}
            {% for list_item in list %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail"
                        alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{ list_item }}" />
                    <div class="card-img-overlay">
                        <h2>
                            <span class="badge badge-primary text-dark">${{ list_item.price | intcomma }}</span>
                        </h2>

                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ list_item.location }}</li>
                        <li class="list-group-item">{{ list_item.business }}</li>
                        <li class="list-group-item">{{ list_item.summary | safe }} </li>
                        <li class="list-group-item">Listing ID : {{ list_item.listing_id }}</li>
                    </ul>
                    <div class="card-body justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'listing:business_listing_single' list_item.listing_id %}">
                                <button type="button" class="btn btn-sm btn-outline-secondary">More
                                    Details..</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
            {% else %}
            <div class="col-md-12">
                <h1 class="text-center">No Listing Found. Try to modify your search</h1>
            </div>
            {% endif %}

        </div>
    </div>
</div>


{% endblock%}

templates/listing/single_business_list.html
{% extends 'layout.html' %}
{% load static %}
{% load humanize %}
{% block listing_li_class %} active {% endblock %}
{% block title %} {{ property.business }} {% endblock %}
{% block content %}

<!-- Page Header -->
<section id="listing" class="py-4">
    <div class="container">
        {% include 'partials/_alert.html' %}
        <a href="{% url 'listing:business_listing' %}" class="btn btn-light mb-4">Back To Listings</a>
        <div class="row">
            <div class="col-md-9">
                <h1>{{ property.business }}</h1>
                <div class="overlay bg-transparent">
                    <h2>
                        <span class="badge
                        {% if property.status == 'Sold Firm' %}
                        badge-danger
                        {% else %}
                        badge-success
                        {% endif %}
                        text-white">Status:
                            {{property.status}} </span>
                    </h2>
                    <!-- Home Main Image -->
                    {% if property.image_main %}
                    <img src="{{ property.image_main.url }}" alt="" class="img-main img-fluid mb-3">
                    {% endif %}
                </div>
                <!-- Thumbnails -->
                <div class="row mb-3 thumbs">
                    {% if property.image_1 %}
                    <div class="col-md-2">
                        <a href="{{ property.image_1.url }}" data-lightbox="home-images">
                            <img src="{{ property.image_1.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                    {% endif %}
                    {% if property.image_2 %}
                    <div class="col-md-2">
                        <a href="{{ property.image_2.url }}" data-lightbox="home-images">
                            <img src="{{ property.image_2.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                    {% endif %}
                    {% if property.image_3 %}
                    <div class="col-md-2">
                        <a href="{{ property.image_3.url }}" data-lightbox="home-images">
                            <img src="{{ property.image_3.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                    {% endif %}
                    {% if property.image_4 %}
                    <div class="col-md-2">
                        <a href="{{ property.image_4.url }}" data-lightbox="home-images">
                            <img src="{{ property.image_4.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                    {% endif %}
                    {% if property.image_5 %}
                    <div class="col-md-2">
                        <a href="{{ property.image_5.url }}" data-lightbox="home-images">
                            <img src="{{ property.image_5.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                    {% endif %}
                    {% if property.image_6 %}
                    <div class="col-md-2">
                        <a href="{{ property.image_6.url }}" data-lightbox="home-images">
                            <img src="{{ property.image_6.url }}" alt="" class="img-fluid">
                        </a>
                    </div>
                    {% endif %}
                </div>
                <div class="my-3">
                    <h5>
                        Listing ID - {{ property.listing_id }}
                    </h5>
                    <h4>
                        Location - {{ property.location }}
                    </h4>
                    <p>
                        For sale - {{ property.business_type }}
                    </p>
                </div>
                <hr>
                <!-- Description -->
                <div class="row mb-5">
                    <div class="col-md-12">
                        {{ property.description | linebreaks}}
                    </div>
                    <div class="col-md-6">
                        <h5>
                            Financing: ${{ property.financing_price | intcomma }}
                        </h5>
                        <h5>
                            Asking: ${{ property.asking_price | intcomma }}
                        </h5>
                    </div>
                    <div class="pt-4 col-md-12">
                        <h6> NDA & Disclaimer </h6>
                        <hr>
                        {{ property.nda_and_disclaimer.disclaimer | safe }}
                    </div>
                </div>
            </div>
            <!-- <div class="col-md-3">
                {% if property.realtor %}
                <div class="card mb-3">
                    <img class="card-img-top" src=" {{ property.realtor.photo.url }}" alt="Seller of the month">
                    <div class="card-body">
                        <h5 class="card-title">Commercial Realtor</h5>
                        <h6 class="text-secondary"> {{ property.realtor.name }} </h6>
                        <h6 class="text-secondary"> {{ property.realtor.phone }} </h6>
                        <h6 class="text-secondary"> {{ property.realtor.email }} </h6>
                    </div>
                </div>
                {% endif %}
                <button class="btn btn-secondary btn-block btn-md" data-toggle="modal" data-target="#inquiryModal">Make
                    An
                    Inquiry</button>
            </div> -->
        </div>
    </div>
</section>

<!-- Inquiry Modal -->
<!-- <div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'contact:contact_model' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="listing_id" value="{{ property.listing_id }}">
                    <div class="form-group">
                        <label for="property_name" class="col-form-label">Property:</label>
                        <input type="text" name="listing_title" class="form-control" value=" {{ property.business }} ">
                    </div>
                    <div class="form-group">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" name="name" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-form-label">Email:</label>
                        <input type="email" name="email" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="phone" class="col-form-label">Phone:</label>
                        <input type="text" name="phone" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="message" class="col-form-label">Message:</label>
                        <textarea name="message" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="g-recaptcha" data-sitekey="6Lfo1IkUAAAAAGIAU_yPaiPD7KI5BGD8A7xecZt_"></div>
                        </div>
                    </div>
                    <hr>
                    <input type="submit" value="Send" class="btn btn-block btn-primary">
                </form>
            </div>
        </div>
    </div>
</div> -->

{% endblock%}